// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProductParams creates a new ListProductParams object
// with the default values initialized.
func NewListProductParams() *ListProductParams {

	return &ListProductParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListProductParamsWithTimeout creates a new ListProductParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListProductParamsWithTimeout(timeout time.Duration) *ListProductParams {

	return &ListProductParams{

		timeout: timeout,
	}
}

// NewListProductParamsWithContext creates a new ListProductParams object
// with the default values initialized, and the ability to set a context for a request
func NewListProductParamsWithContext(ctx context.Context) *ListProductParams {

	return &ListProductParams{

		Context: ctx,
	}
}

// NewListProductParamsWithHTTPClient creates a new ListProductParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListProductParamsWithHTTPClient(client *http.Client) *ListProductParams {

	return &ListProductParams{
		HTTPClient: client,
	}
}

/*ListProductParams contains all the parameters to send to the API endpoint
for the list product operation typically these are written to a http.Request
*/
type ListProductParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list product params
func (o *ListProductParams) WithTimeout(timeout time.Duration) *ListProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list product params
func (o *ListProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list product params
func (o *ListProductParams) WithContext(ctx context.Context) *ListProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list product params
func (o *ListProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list product params
func (o *ListProductParams) WithHTTPClient(client *http.Client) *ListProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list product params
func (o *ListProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
